[package]
name = "owe-types"
version.workspace = true
module = "wescene.types"

[library]
archive = "owe-types"
discovery = "explicit"
sources = ["types.cppm", "types.cpp"]

[usage]
public-options = ["-fPIC", "-fsized-deallocation"]
private-options = [
  "-Wall",
  "-Wextra",
  "-Wpedantic",
  "-Wno-missing-field-initializers",
  "-Wno-gnu-zero-variadic-macro-arguments",
]
private-linker-options = ["-ldl"]

[dependencies.owe-core]
path = "../../Core"
visibility = "public"

[dependencies.rstd-std]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.rstd-cppstd]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"
